dist: xenial
language: node_js
node_js:
  - "10"

install: true

cache:
  directories:
    - node_modules

branches:
  only:
      - gh-pages
      - /.*/

stages:
  - "Lint and build"
  - "Deploy"

jobs:
  include:
    - stage: "Lint and build"
      script:
        - npm install
        - npm run lint

    - stage: "Lint and build"
      script:
        - npm install
        - npm run dist

    - stage: "Deploy"
      script:
        - npm install
        - npm run dist
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: dist
        on:
          branch: deploy-to-gh-pages # TODO: master
